In [14]:
import re
import requests

from bs4 import BeautifulSoup

In [2]:
url = "https://finance.yahoo.com/quote/AAPL/history"
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}
response = requests.get(url, headers=headers)
print(response.status_code)

200

In [3]:
soup = BeautifulSoup(response.content, 'html.parser')

In [4]:
page_elements = soup.find_all('td', class_='yf-1jecxey')

In [5]:
page_elements = [element.text for element in page_elements]
page_elements

['Apr 28, 2025',
 '210.06',
 '211.50',
 '208.73',
 '209.74',
 '209.74',
 '10,697,544',
 'Apr 25, 2025',
 '206.37',
 '209.75',
 '206.20',
 '209.28',
 '209.28',
 '38,198,600',
 'Apr 24, 2025',
 '204.89',
 '208.83',
 '202.94',
 '208.37',
 '208.37',
 '47,311,000',
 'Apr 23, 2025',
 '206.00',
 '208.00',
 '202.80',
 '204.60',
 '204.60',
 '52,929,200',
 'Apr 22, 2025',
 '196.12',
 '201.59',
 '195.97',
 '199.74',
 '199.74',
 '52,976,400',
 'Apr 21, 2025',
 '193.27',
 '193.80',
 '189.81',
 '193.16',
 '193.16',
 '46,742,500',
 'Apr 17, 2025',
 '197.20',
 '198.83',
 '194.42',
 '196.98',
 '196.98',
 '51,334,300',
 'Apr 16, 2025',
 '198.36',
 '200.70',
 '192.37',
 '194.27',
 '194.27',
 '59,732,400',
 'Apr 15, 2025',
 '201.86',
 '203.51',
 '199.80',
 '202.14',
 '202.14',
 '51,343,900',
 'Apr 14, 2025',
 '211.44',
 '212.94',
 '201.16',
 '202.52',
 '202.52',
 '101,352,900',
 'Apr 11, 2025',
 '186.10',
 '199.54',
 '186.06',
 '198.15',
 '198.15',
 '87,435,900',
 'Apr 10, 2025',
 '189.07',
 '194.78',
 '183.00',
 '190.42',
 '190.42',
 '121,880,000',
 'Apr 9, 2025',
 '171.95',
 '200.61',
 '171.89',
 '198.85',
 '198.85',
 '184,395,900',
 'Apr 8, 2025',
 '186.70',
 '190.34',
 '169.21',
 '172.42',
 '172.42',
 '120,859,500',
 'Apr 7, 2025',
 '177.20',
 '194.15',
 '174.62',
 '181.46',
 '181.46',
 '160,466,300',
 'Apr 4, 2025',
 '193.89',
 '199.88',
 '187.34',
 '188.38',
 '188.38',
 '125,910,900',
 'Apr 3, 2025',
 '205.54',
 '207.49',
 '201.25',
 '203.19',
 '203.19',
 '103,419,000',
 'Apr 2, 2025',
 '221.32',
 '225.19',
 '221.02',
 '223.89',
 '223.89',
 '35,905,900',
 'Apr 1, 2025',
 '219.81',
 '223.68',
 '218.90',
 '223.19',
 '223.19',
 '36,412,700',
 'Mar 31, 2025',
 '217.01',
 '225.62',
 '216.23',
 '222.13',
 '222.13',
 '65,299,300',
 'Mar 28, 2025',
 '221.67',
 '223.81',
 '217.68',
 '217.90',
 '217.90',
 '39,818,600',
 'Mar 27, 2025',
 '221.39',
 '224.99',
 '220.56',
 '223.85',
 '223.85',
 '37,094,800',
 'Mar 26, 2025',
 '223.51',
 '225.02',
 '220.47',
 '221.53',
 '221.53',
 '34,466,100',
 'Mar 25, 2025',
 '220.77',
 '224.10',
 '220.08',
 '223.75',
 '223.75',
 '34,493,600',
 'Mar 24, 2025',
 '221.00',
 '221.48',
 '218.58',
 '220.73',
 '220.73',
 '44,299,500',
 'Mar 21, 2025',
 '211.56',
 '218.84',
 '211.28',
 '218.27',
 '218.27',
 '94,127,800',
 'Mar 20, 2025',
 '213.99',
 '217.49',
 '212.22',
 '214.10',
 '214.10',
 '48,862,900',
 'Mar 19, 2025',
 '214.22',
 '218.76',
 '213.75',
 '215.24',
 '215.24',
 '54,385,400',
 'Mar 18, 2025',
 '214.16',
 '215.15',
 '211.49',
 '212.69',
 '212.69',
 '42,432,400',
 'Mar 17, 2025',
 '213.31',
 '215.22',
 '209.97',
 '214.00',
 '214.00',
 '48,073,400',
 'Mar 14, 2025',
 '211.25',
 '213.95',
 '209.58',
 '213.49',
 '213.49',
 '60,107,600',
 'Mar 13, 2025',
 '215.95',
 '216.84',
 '208.42',
 '209.68',
 '209.68',
 '61,368,300',
 'Mar 12, 2025',
 '220.14',
 '221.75',
 '214.91',
 '216.98',
 '216.98',
 '62,547,500',
 'Mar 11, 2025',
 '223.81',
 '225.84',
 '217.45',
 '220.84',
 '220.84',
 '76,137,400',
 'Mar 10, 2025',
 '235.54',
 '236.16',
 '224.22',
 '227.48',
 '227.48',
 '72,071,200',
 'Mar 7, 2025',
 '235.11',
 '241.37',
 '234.76',
 '239.07',
 '239.07',
 '46,273,600',
 'Mar 6, 2025',
 '234.44',
 '237.86',
 '233.16',
 '235.33',
 '235.33',
 '45,170,400',
 'Mar 5, 2025',
 '235.42',
 '236.55',
 '229.23',
 '235.74',
 '235.74',
 '47,227,600',
 'Mar 4, 2025',
 '237.71',
 '240.07',
 '234.68',
 '235.93',
 '235.93',
 '53,798,100',
 'Mar 3, 2025',
 '241.79',
 '244.03',
 '236.11',
 '238.03',
 '238.03',
 '47,184,000',
 'Feb 28, 2025',
 '236.95',
 '242.09',
 '230.20',
 '241.84',
 '241.84',
 '56,833,400',
 'Feb 27, 2025',
 '239.41',
 '242.46',
 '237.06',
 '237.30',
 '237.30',
 '41,153,600',
 'Feb 26, 2025',
 '244.33',
 '244.98',
 '239.13',
 '240.36',
 '240.36',
 '44,433,600',
 'Feb 25, 2025',
 '248.00',
 '250.00',
 '244.91',
 '247.04',
 '247.04',
 '48,013,300',
 'Feb 24, 2025',
 '244.93',
 '248.86',
 '244.42',
 '247.10',
 '247.10',
 '51,326,400',
 'Feb 21, 2025',
 '245.95',
 '248.69',
 '245.22',
 '245.55',
 '245.55',
 '53,197,400',
 'Feb 20, 2025',
 '244.94',
 '246.78',
 '244.29',
 '245.83',
 '245.83',
 '32,316,900',
 'Feb 19, 2025',
 '244.66',
 '246.01',
 '243.16',
 '244.87',
 '244.87',
 '32,204,200',
 'Feb 18, 2025',
 '244.15',
 '245.18',
 '241.84',
 '244.47',
 '244.47',
 '48,822,500',
 'Feb 14, 2025',
 '241.25',
 '245.55',
 '240.99',
 '244.60',
 '244.60',
 '40,896,200',
 'Feb 13, 2025',
 '236.91',
 '242.34',
 '235.57',
 '241.53',
 '241.53',
 '53,614,100',
 'Feb 12, 2025',
 '231.20',
 '236.96',
 '230.68',
 '236.87',
 '236.87',
 '45,243,300',
 'Feb 11, 2025',
 '228.20',
 '235.23',
 '228.13',
 '232.62',
 '232.62',
 '53,718,400',
 'Feb 10, 2025',
 '0.25 Dividend ',
 'Feb 10, 2025',
 '229.57',
 '230.59',
 '227.20',
 '227.65',
 '227.65',
 '33,115,600',
 'Feb 7, 2025',
 '232.60',
 '234.00',
 '227.26',
 '227.63',
 '227.38',
 '39,707,200',
 'Feb 6, 2025',
 '231.29',
 '233.80',
 '230.43',
 '233.22',
 '232.96',
 '29,925,300',
 'Feb 5, 2025',
 '228.53',
 '232.67',
 '228.27',
 '232.47',
 '232.21',
 '39,620,300',
 'Feb 4, 2025',
 '227.25',
 '233.13',
 '226.65',
 '232.80',
 '232.54',
 '45,067,300',
 'Feb 3, 2025',
 '229.99',
 '231.83',
 '225.70',
 '228.01',
 '227.76',
 '73,063,300',
 'Jan 31, 2025',
 '247.19',
 '247.19',
 '233.44',
 '236.00',
 '235.74',
 '101,075,100',
 'Jan 30, 2025',
 '238.67',
 '240.79',
 '237.21',
 '237.59',
 '237.33',
 '55,658,300',
 'Jan 29, 2025',
 '234.12',
 '239.86',
 '234.01',
 '239.36',
 '239.10',
 '45,486,100',
 'Jan 28, 2025',
 '230.85',
 '240.19',
 '230.81',
 '238.26',
 '238.00',
 '75,707,600',
 'Jan 27, 2025',
 '224.02',
 '232.15',
 '223.98',
 '229.86',
 '229.61',
 '94,863,400',
 'Jan 24, 2025',
 '224.78',
 '225.63',
 '221.41',
 '222.78',
 '222.54',
 '54,697,900',
 'Jan 23, 2025',
 '224.74',
 '227.03',
 '222.30',
 '223.66',
 '223.41',
 '60,234,800',
 'Jan 22, 2025',
 '219.79',
 '224.12',
 '219.79',
 '223.83',
 '223.58',
 '64,126,500',
 'Jan 21, 2025',
 '224.00',
 '224.42',
 '219.38',
 '222.64',
 '222.40',
 '98,070,400',
 'Jan 17, 2025',
 '232.12',
 '232.29',
 '228.48',
 '229.98',
 '229.73',
 '68,488,300',
 'Jan 16, 2025',
 '237.35',
 '238.01',
 '228.03',
 '228.26',
 '228.01',
 '71,759,100',
 'Jan 15, 2025',
 '234.64',
 '238.96',
 '234.43',
 '237.87',
 '237.61',
 '39,832,000',
 'Jan 14, 2025',
 '234.75',
 '236.12',
 '232.47',
 '233.28',
 '233.02',
 '39,435,300',
 'Jan 13, 2025',
 '233.53',
 '234.67',
 '229.72',
 '234.40',
 '234.14',
 '49,630,700',
 'Jan 10, 2025',
 '240.01',
 '240.16',
 '233.00',
 '236.85',
 '236.59',
 '61,710,900',
 'Jan 8, 2025',
 '241.92',
 '243.71',
 '240.05',
 '242.70',
 '242.43',
 '37,628,900',
 'Jan 7, 2025',
 '242.98',
 '245.55',
 '241.35',
 '242.21',
 '241.94',
 '40,856,000',
 'Jan 6, 2025',
 '244.31',
 '247.33',
 '243.20',
 '245.00',
 '244.73',
 '45,045,600',
 'Jan 3, 2025',
 '243.36',
 '244.18',
 '241.89',
 '243.36',
 '243.09',
 '40,244,100',
 'Jan 2, 2025',
 '248.93',
 '249.10',
 '241.82',
 '243.85',
 '243.58',
 '55,740,700',
 'Dec 31, 2024',
 '252.44',
 '253.28',
 '249.43',
 '250.42',
 '250.14',
 '39,480,700',
 'Dec 30, 2024',
 '252.23',
 '253.50',
 '250.75',
 '252.20',
 '251.92',
 '35,557,500',
 'Dec 27, 2024',
 '257.83',
 '258.70',
 '253.06',
 '255.59',
 '255.31',
 '42,355,300',
 'Dec 26, 2024',
 '258.19',
 '260.10',
 '257.63',
 '259.02',
 '258.74',
 '27,237,100',
 'Dec 24, 2024',
 '255.49',
 '258.21',
 '255.29',
 '258.20',
 '257.92',
 '23,234,700',
 'Dec 23, 2024',
 '254.77',
 '255.65',
 '253.45',
 '255.27',
 '254.99',
 '40,858,800',
 'Dec 20, 2024',
 '248.04',
 '255.00',
 '245.69',
 '254.49',
 '254.21',
 '147,495,300',
 'Dec 19, 2024',
 '247.50',
 '252.00',
 '247.09',
 '249.79',
 '249.52',
 '60,882,300',
 'Dec 18, 2024',
 '252.16',
 '254.28',
 '247.74',
 '248.05',
 '247.78',
 '56,774,100',
 'Dec 17, 2024',
 '250.08',
 '253.83',
 '249.78',
 '253.48',
 '253.20',
 '51,356,400',
 'Dec 16, 2024',
 '247.99',
 '251.38',
 '247.65',
 '251.04',
 '250.76',
 '51,694,800',
 'Dec 13, 2024',
 '247.82',
 '249.29',
 '246.24',
 '248.13',
 '247.86',
 '33,155,300',
 'Dec 12, 2024',
 '246.89',
 '248.74',
 '245.68',
 '247.96',
 '247.69',
 '32,777,500',
 'Dec 11, 2024',
 '247.96',
 '250.80',
 '246.26',
 '246.49',
 '246.22',
 '45,205,800',
 'Dec 10, 2024',
 '246.89',
 '248.21',
 '245.34',
 '247.77',
 '247.50',
 '36,914,800',
 'Dec 9, 2024',
 '241.83',
 '247.24',
 '241.75',
 '246.75',
 '246.48',
 '44,649,200',
 'Dec 6, 2024',
 '242.91',
 '244.63',
 '242.08',
 '242.84',
 '242.57',
 '36,870,600',
 'Dec 5, 2024',
 '243.99',
 '244.54',
 '242.13',
 '243.04',
 '242.77',
 '40,033,900',
 'Dec 4, 2024',
 '242.87',
 '244.11',
 '241.25',
 '243.01',
 '242.74',
 '44,383,900',
 'Dec 3, 2024',
 '239.81',
 '242.76',
 '238.90',
 '242.65',
 '242.38',
 '38,861,000',
 'Dec 2, 2024',
 '237.27',
 '240.79',
 '237.16',
 '239.59',
 '239.33',
 '48,137,100',
 'Nov 29, 2024',
 '234.81',
 '237.81',
 '233.97',
 '237.33',
 '237.07',
 '28,481,400',
 'Nov 27, 2024',
 '234.47',
 '235.69',
 '233.81',
 '234.93',
 '234.67',
 '33,498,400',
 'Nov 26, 2024',
 '233.33',
 '235.57',
 '233.33',
 '235.06',
 '234.80',
 '45,986,200',
 'Nov 25, 2024',
 '231.46',
 '233.25',
 '229.74',
 '232.87',
 '232.61',
 '90,152,800',
 'Nov 22, 2024',
 '228.06',
 '230.72',
 '228.06',
 '229.87',
 '229.62',
 '38,168,300',
 'Nov 21, 2024',
 '228.88',
 '230.16',
 '225.71',
 '228.52',
 '228.27',
 '42,108,300',
 'Nov 20, 2024',
 '228.06',
 '229.93',
 '225.89',
 '229.00',
 '228.75',
 '35,169,600',
 'Nov 19, 2024',
 '226.98',
 '230.16',
 '226.66',
 '228.28',
 '228.03',
 '36,211,800',
 'Nov 18, 2024',
 '225.25',
 '229.74',
 '225.17',
 '228.02',
 '227.77',
 '44,686,000',
 'Nov 15, 2024',
 '226.40',
 '226.92',
 '224.27',
 '225.00',
 '224.75',
 '47,923,700',
 'Nov 14, 2024',
 '225.02',
 '228.87',
 '225.00',
 '228.22',
 '227.97',
 '44,923,900',
 'Nov 13, 2024',
 '224.01',
 '226.65',
 '222.76',
 '225.12',
 '224.87',
 '48,566,200',
 'Nov 12, 2024',
 '224.55',
 '225.59',
 '223.36',
 '224.23',
 '223.98',
 '40,398,300',
 'Nov 11, 2024',
 '225.00',
 '225.70',
 '221.50',
 '224.23',
 '223.98',
 '42,005,600',
 'Nov 8, 2024',
 '0.25 Dividend ',
 'Nov 8, 2024',
 '227.17',
 '228.66',
 '226.41',
 '226.96',
 '226.71',
 '38,328,800',
 'Nov 7, 2024',
 '224.63',
 '227.88',
 '224.57',
 '227.48',
 '226.98',
 '42,137,700',
 'Nov 6, 2024',
 '222.61',
 '226.07',
 '221.19',
 '222.72',
 '222.23',
 '54,561,100',
 'Nov 5, 2024',
 '221.80',
 '223.95',
 '221.14',
 '223.45',
 '222.96',
 '28,111,300',
 'Nov 4, 2024',
 '220.99',
 '222.79',
 '219.71',
 '222.01',
 '221.52',
 '44,944,500',
 'Nov 1, 2024',
 '220.97',
 '225.35',
 '220.27',
 '222.91',
 '222.42',
 '65,276,700',
 'Oct 31, 2024',
 '229.34',
 '229.83',
 '225.37',
 '225.91',
 '225.41',
 '64,370,100',
 'Oct 30, 2024',
 '232.61',
 '233.47',
 '229.55',
 '230.10',
 '229.59',
 '47,070,900',
 'Oct 29, 2024',
 '233.10',
 '234.33',
 '232.32',
 '233.67',
 '233.16',
 '35,417,200',
 'Oct 28, 2024',
 '233.32',
 '234.73',
 '232.55',
 '233.40',
 '232.89',
 '36,087,100',
 'Oct 25, 2024',
 '229.74',
 '233.22',
 '229.57',
 '231.41',
 '230.90',
 '38,802,300',
 'Oct 24, 2024',
 '229.98',
 '230.82',
 '228.41',
 '230.57',
 '230.06',
 '31,109,500',
 'Oct 23, 2024',
 '234.08',
 '235.14',
 '227.76',
 '230.76',
 '230.25',
 '52,287,000',
 'Oct 22, 2024',
 '233.89',
 '236.22',
 '232.60',
 '235.86',
 '235.34',
 '38,846,600',
 'Oct 21, 2024',
 '234.45',
 '236.85',
 '234.45',
 '236.48',
 '235.96',
 '36,254,500',
 'Oct 18, 2024',
 '236.18',
 '236.18',
 '234.01',
 '235.00',
 '234.48',
 '46,431,500',
 'Oct 17, 2024',
 '233.43',
 '233.85',
 '230.52',
 '232.15',
 '231.64',
 '32,993,800',
 'Oct 16, 2024',
 '231.60',
 '232.12',
 '229.84',
 '231.78',
 '231.27',
 '34,082,200',
 'Oct 15, 2024',
 '233.61',
 '237.49',
 '232.37',
 '233.85',
 '233.34',
 '64,751,400',
 'Oct 14, 2024',
 '228.70',
 '231.73',
 '228.60',
 '231.30',
 '230.79',
 '39,882,100',
 'Oct 11, 2024',
 '229.30',
 '229.41',
 '227.34',
 '227.55',
 '227.05',
 '31,759,200',
 'Oct 10, 2024',
 '227.78',
 '229.50',
 '227.17',
 '229.04',
 '228.54',
 '28,183,500',
 'Oct 9, 2024',
 '225.23',
 '229.75',
 '224.83',
 '229.54',
 '229.04',
 '33,591,100',
 'Oct 8, 2024',
 '224.30',
 '225.98',
 '223.25',
 '225.77',
 '225.27',
 '31,855,700',
 'Oct 7, 2024',
 '224.50',
 '225.69',
 '221.33',
 '221.69',
 '221.20',
 '39,505,400',
 'Oct 4, 2024',
 '227.90',
 '228.00',
 '224.13',
 '226.80',
 '226.30',
 '37,245,100',
 'Oct 3, 2024',
 '225.14',
 '226.81',
 '223.32',
 '225.67',
 '225.17',
 '34,044,200',
 'Oct 2, 2024',
 '225.89',
 '227.37',
 '223.02',
 '226.78',
 '226.28',
 '32,880,600',
 'Oct 1, 2024',
 '229.52',
 ...]

In [6]:
for i in range(0, 100, 7):
    print(i)

0
7
14
21
28
35
42
49
56
63
70
77
84
91
98

In [7]:
def parse_data(input_list):
    parsed_data = []
    for i in range(0, len(input_list), 7):
        if i+6 < len(input_list):  # cek apakah cukup elemen
            temp_dict = {
                "Date": input_list[i],
                "Open": input_list[i+1],
                "High": input_list[i+2],
                "Low": input_list[i+3],
                "Close": input_list[i+4],
                "Volume": input_list[i+6]
            }
            parsed_data.append(temp_dict)
        else:
            # Kalau data kurang dari 7 elemen, dilewati
            print(f"Skipping incomplete data at index {i}")
    return parsed_data

In [ ]:
page_elements.remove("0.25 Dividend ")

In [74]:
for i, element in enumerate(page_elements):
    if element == 'Feb 10, 2025':
        print(i)

371
372

In [75]:
page_elements.pop(371)

'Feb 10, 2025'

In [76]:
page_elements[370:380]

['53,718,400',
 'Feb 10, 2025',
 '229.57',
 '230.59',
 '227.20',
 '227.65',
 '227.65',
 '33,115,600',
 'Feb 7, 2025',
 '232.60']

In [10]:
page_elements[-7:]

['Apr 29, 2024',
 '173.37',
 '176.03',
 '173.10',
 '173.50',
 '172.68',
 '68,169,400']

In [77]:
page_elements

['Apr 28, 2025',
 '210.06',
 '211.50',
 '208.73',
 '209.74',
 '209.74',
 '10,697,544',
 'Apr 25, 2025',
 '206.37',
 '209.75',
 '206.20',
 '209.28',
 '209.28',
 '38,198,600',
 'Apr 24, 2025',
 '204.89',
 '208.83',
 '202.94',
 '208.37',
 '208.37',
 '47,311,000',
 'Apr 23, 2025',
 '206.00',
 '208.00',
 '202.80',
 '204.60',
 '204.60',
 '52,929,200',
 'Apr 22, 2025',
 '196.12',
 '201.59',
 '195.97',
 '199.74',
 '199.74',
 '52,976,400',
 'Apr 21, 2025',
 '193.27',
 '193.80',
 '189.81',
 '193.16',
 '193.16',
 '46,742,500',
 'Apr 17, 2025',
 '197.20',
 '198.83',
 '194.42',
 '196.98',
 '196.98',
 '51,334,300',
 'Apr 16, 2025',
 '198.36',
 '200.70',
 '192.37',
 '194.27',
 '194.27',
 '59,732,400',
 'Apr 15, 2025',
 '201.86',
 '203.51',
 '199.80',
 '202.14',
 '202.14',
 '51,343,900',
 'Apr 14, 2025',
 '211.44',
 '212.94',
 '201.16',
 '202.52',
 '202.52',
 '101,352,900',
 'Apr 11, 2025',
 '186.10',
 '199.54',
 '186.06',
 '198.15',
 '198.15',
 '87,435,900',
 'Apr 10, 2025',
 '189.07',
 '194.78',
 '183.00',
 '190.42',
 '190.42',
 '121,880,000',
 'Apr 9, 2025',
 '171.95',
 '200.61',
 '171.89',
 '198.85',
 '198.85',
 '184,395,900',
 'Apr 8, 2025',
 '186.70',
 '190.34',
 '169.21',
 '172.42',
 '172.42',
 '120,859,500',
 'Apr 7, 2025',
 '177.20',
 '194.15',
 '174.62',
 '181.46',
 '181.46',
 '160,466,300',
 'Apr 4, 2025',
 '193.89',
 '199.88',
 '187.34',
 '188.38',
 '188.38',
 '125,910,900',
 'Apr 3, 2025',
 '205.54',
 '207.49',
 '201.25',
 '203.19',
 '203.19',
 '103,419,000',
 'Apr 2, 2025',
 '221.32',
 '225.19',
 '221.02',
 '223.89',
 '223.89',
 '35,905,900',
 'Apr 1, 2025',
 '219.81',
 '223.68',
 '218.90',
 '223.19',
 '223.19',
 '36,412,700',
 'Mar 31, 2025',
 '217.01',
 '225.62',
 '216.23',
 '222.13',
 '222.13',
 '65,299,300',
 'Mar 28, 2025',
 '221.67',
 '223.81',
 '217.68',
 '217.90',
 '217.90',
 '39,818,600',
 'Mar 27, 2025',
 '221.39',
 '224.99',
 '220.56',
 '223.85',
 '223.85',
 '37,094,800',
 'Mar 26, 2025',
 '223.51',
 '225.02',
 '220.47',
 '221.53',
 '221.53',
 '34,466,100',
 'Mar 25, 2025',
 '220.77',
 '224.10',
 '220.08',
 '223.75',
 '223.75',
 '34,493,600',
 'Mar 24, 2025',
 '221.00',
 '221.48',
 '218.58',
 '220.73',
 '220.73',
 '44,299,500',
 'Mar 21, 2025',
 '211.56',
 '218.84',
 '211.28',
 '218.27',
 '218.27',
 '94,127,800',
 'Mar 20, 2025',
 '213.99',
 '217.49',
 '212.22',
 '214.10',
 '214.10',
 '48,862,900',
 'Mar 19, 2025',
 '214.22',
 '218.76',
 '213.75',
 '215.24',
 '215.24',
 '54,385,400',
 'Mar 18, 2025',
 '214.16',
 '215.15',
 '211.49',
 '212.69',
 '212.69',
 '42,432,400',
 'Mar 17, 2025',
 '213.31',
 '215.22',
 '209.97',
 '214.00',
 '214.00',
 '48,073,400',
 'Mar 14, 2025',
 '211.25',
 '213.95',
 '209.58',
 '213.49',
 '213.49',
 '60,107,600',
 'Mar 13, 2025',
 '215.95',
 '216.84',
 '208.42',
 '209.68',
 '209.68',
 '61,368,300',
 'Mar 12, 2025',
 '220.14',
 '221.75',
 '214.91',
 '216.98',
 '216.98',
 '62,547,500',
 'Mar 11, 2025',
 '223.81',
 '225.84',
 '217.45',
 '220.84',
 '220.84',
 '76,137,400',
 'Mar 10, 2025',
 '235.54',
 '236.16',
 '224.22',
 '227.48',
 '227.48',
 '72,071,200',
 'Mar 7, 2025',
 '235.11',
 '241.37',
 '234.76',
 '239.07',
 '239.07',
 '46,273,600',
 'Mar 6, 2025',
 '234.44',
 '237.86',
 '233.16',
 '235.33',
 '235.33',
 '45,170,400',
 'Mar 5, 2025',
 '235.42',
 '236.55',
 '229.23',
 '235.74',
 '235.74',
 '47,227,600',
 'Mar 4, 2025',
 '237.71',
 '240.07',
 '234.68',
 '235.93',
 '235.93',
 '53,798,100',
 'Mar 3, 2025',
 '241.79',
 '244.03',
 '236.11',
 '238.03',
 '238.03',
 '47,184,000',
 'Feb 28, 2025',
 '236.95',
 '242.09',
 '230.20',
 '241.84',
 '241.84',
 '56,833,400',
 'Feb 27, 2025',
 '239.41',
 '242.46',
 '237.06',
 '237.30',
 '237.30',
 '41,153,600',
 'Feb 26, 2025',
 '244.33',
 '244.98',
 '239.13',
 '240.36',
 '240.36',
 '44,433,600',
 'Feb 25, 2025',
 '248.00',
 '250.00',
 '244.91',
 '247.04',
 '247.04',
 '48,013,300',
 'Feb 24, 2025',
 '244.93',
 '248.86',
 '244.42',
 '247.10',
 '247.10',
 '51,326,400',
 'Feb 21, 2025',
 '245.95',
 '248.69',
 '245.22',
 '245.55',
 '245.55',
 '53,197,400',
 'Feb 20, 2025',
 '244.94',
 '246.78',
 '244.29',
 '245.83',
 '245.83',
 '32,316,900',
 'Feb 19, 2025',
 '244.66',
 '246.01',
 '243.16',
 '244.87',
 '244.87',
 '32,204,200',
 'Feb 18, 2025',
 '244.15',
 '245.18',
 '241.84',
 '244.47',
 '244.47',
 '48,822,500',
 'Feb 14, 2025',
 '241.25',
 '245.55',
 '240.99',
 '244.60',
 '244.60',
 '40,896,200',
 'Feb 13, 2025',
 '236.91',
 '242.34',
 '235.57',
 '241.53',
 '241.53',
 '53,614,100',
 'Feb 12, 2025',
 '231.20',
 '236.96',
 '230.68',
 '236.87',
 '236.87',
 '45,243,300',
 'Feb 11, 2025',
 '228.20',
 '235.23',
 '228.13',
 '232.62',
 '232.62',
 '53,718,400',
 'Feb 10, 2025',
 '229.57',
 '230.59',
 '227.20',
 '227.65',
 '227.65',
 '33,115,600',
 'Feb 7, 2025',
 '232.60',
 '234.00',
 '227.26',
 '227.63',
 '227.38',
 '39,707,200',
 'Feb 6, 2025',
 '231.29',
 '233.80',
 '230.43',
 '233.22',
 '232.96',
 '29,925,300',
 'Feb 5, 2025',
 '228.53',
 '232.67',
 '228.27',
 '232.47',
 '232.21',
 '39,620,300',
 'Feb 4, 2025',
 '227.25',
 '233.13',
 '226.65',
 '232.80',
 '232.54',
 '45,067,300',
 'Feb 3, 2025',
 '229.99',
 '231.83',
 '225.70',
 '228.01',
 '227.76',
 '73,063,300',
 'Jan 31, 2025',
 '247.19',
 '247.19',
 '233.44',
 '236.00',
 '235.74',
 '101,075,100',
 'Jan 30, 2025',
 '238.67',
 '240.79',
 '237.21',
 '237.59',
 '237.33',
 '55,658,300',
 'Jan 29, 2025',
 '234.12',
 '239.86',
 '234.01',
 '239.36',
 '239.10',
 '45,486,100',
 'Jan 28, 2025',
 '230.85',
 '240.19',
 '230.81',
 '238.26',
 '238.00',
 '75,707,600',
 'Jan 27, 2025',
 '224.02',
 '232.15',
 '223.98',
 '229.86',
 '229.61',
 '94,863,400',
 'Jan 24, 2025',
 '224.78',
 '225.63',
 '221.41',
 '222.78',
 '222.54',
 '54,697,900',
 'Jan 23, 2025',
 '224.74',
 '227.03',
 '222.30',
 '223.66',
 '223.41',
 '60,234,800',
 'Jan 22, 2025',
 '219.79',
 '224.12',
 '219.79',
 '223.83',
 '223.58',
 '64,126,500',
 'Jan 21, 2025',
 '224.00',
 '224.42',
 '219.38',
 '222.64',
 '222.40',
 '98,070,400',
 'Jan 17, 2025',
 '232.12',
 '232.29',
 '228.48',
 '229.98',
 '229.73',
 '68,488,300',
 'Jan 16, 2025',
 '237.35',
 '238.01',
 '228.03',
 '228.26',
 '228.01',
 '71,759,100',
 'Jan 15, 2025',
 '234.64',
 '238.96',
 '234.43',
 '237.87',
 '237.61',
 '39,832,000',
 'Jan 14, 2025',
 '234.75',
 '236.12',
 '232.47',
 '233.28',
 '233.02',
 '39,435,300',
 'Jan 13, 2025',
 '233.53',
 '234.67',
 '229.72',
 '234.40',
 '234.14',
 '49,630,700',
 'Jan 10, 2025',
 '240.01',
 '240.16',
 '233.00',
 '236.85',
 '236.59',
 '61,710,900',
 'Jan 8, 2025',
 '241.92',
 '243.71',
 '240.05',
 '242.70',
 '242.43',
 '37,628,900',
 'Jan 7, 2025',
 '242.98',
 '245.55',
 '241.35',
 '242.21',
 '241.94',
 '40,856,000',
 'Jan 6, 2025',
 '244.31',
 '247.33',
 '243.20',
 '245.00',
 '244.73',
 '45,045,600',
 'Jan 3, 2025',
 '243.36',
 '244.18',
 '241.89',
 '243.36',
 '243.09',
 '40,244,100',
 'Jan 2, 2025',
 '248.93',
 '249.10',
 '241.82',
 '243.85',
 '243.58',
 '55,740,700',
 'Dec 31, 2024',
 '252.44',
 '253.28',
 '249.43',
 '250.42',
 '250.14',
 '39,480,700',
 'Dec 30, 2024',
 '252.23',
 '253.50',
 '250.75',
 '252.20',
 '251.92',
 '35,557,500',
 'Dec 27, 2024',
 '257.83',
 '258.70',
 '253.06',
 '255.59',
 '255.31',
 '42,355,300',
 'Dec 26, 2024',
 '258.19',
 '260.10',
 '257.63',
 '259.02',
 '258.74',
 '27,237,100',
 'Dec 24, 2024',
 '255.49',
 '258.21',
 '255.29',
 '258.20',
 '257.92',
 '23,234,700',
 'Dec 23, 2024',
 '254.77',
 '255.65',
 '253.45',
 '255.27',
 '254.99',
 '40,858,800',
 'Dec 20, 2024',
 '248.04',
 '255.00',
 '245.69',
 '254.49',
 '254.21',
 '147,495,300',
 'Dec 19, 2024',
 '247.50',
 '252.00',
 '247.09',
 '249.79',
 '249.52',
 '60,882,300',
 'Dec 18, 2024',
 '252.16',
 '254.28',
 '247.74',
 '248.05',
 '247.78',
 '56,774,100',
 'Dec 17, 2024',
 '250.08',
 '253.83',
 '249.78',
 '253.48',
 '253.20',
 '51,356,400',
 'Dec 16, 2024',
 '247.99',
 '251.38',
 '247.65',
 '251.04',
 '250.76',
 '51,694,800',
 'Dec 13, 2024',
 '247.82',
 '249.29',
 '246.24',
 '248.13',
 '247.86',
 '33,155,300',
 'Dec 12, 2024',
 '246.89',
 '248.74',
 '245.68',
 '247.96',
 '247.69',
 '32,777,500',
 'Dec 11, 2024',
 '247.96',
 '250.80',
 '246.26',
 '246.49',
 '246.22',
 '45,205,800',
 'Dec 10, 2024',
 '246.89',
 '248.21',
 '245.34',
 '247.77',
 '247.50',
 '36,914,800',
 'Dec 9, 2024',
 '241.83',
 '247.24',
 '241.75',
 '246.75',
 '246.48',
 '44,649,200',
 'Dec 6, 2024',
 '242.91',
 '244.63',
 '242.08',
 '242.84',
 '242.57',
 '36,870,600',
 'Dec 5, 2024',
 '243.99',
 '244.54',
 '242.13',
 '243.04',
 '242.77',
 '40,033,900',
 'Dec 4, 2024',
 '242.87',
 '244.11',
 '241.25',
 '243.01',
 '242.74',
 '44,383,900',
 'Dec 3, 2024',
 '239.81',
 '242.76',
 '238.90',
 '242.65',
 '242.38',
 '38,861,000',
 'Dec 2, 2024',
 '237.27',
 '240.79',
 '237.16',
 '239.59',
 '239.33',
 '48,137,100',
 'Nov 29, 2024',
 '234.81',
 '237.81',
 '233.97',
 '237.33',
 '237.07',
 '28,481,400',
 'Nov 27, 2024',
 '234.47',
 '235.69',
 '233.81',
 '234.93',
 '234.67',
 '33,498,400',
 'Nov 26, 2024',
 '233.33',
 '235.57',
 '233.33',
 '235.06',
 '234.80',
 '45,986,200',
 'Nov 25, 2024',
 '231.46',
 '233.25',
 '229.74',
 '232.87',
 '232.61',
 '90,152,800',
 'Nov 22, 2024',
 '228.06',
 '230.72',
 '228.06',
 '229.87',
 '229.62',
 '38,168,300',
 'Nov 21, 2024',
 '228.88',
 '230.16',
 '225.71',
 '228.52',
 '228.27',
 '42,108,300',
 'Nov 20, 2024',
 '228.06',
 '229.93',
 '225.89',
 '229.00',
 '228.75',
 '35,169,600',
 'Nov 19, 2024',
 '226.98',
 '230.16',
 '226.66',
 '228.28',
 '228.03',
 '36,211,800',
 'Nov 18, 2024',
 '225.25',
 '229.74',
 '225.17',
 '228.02',
 '227.77',
 '44,686,000',
 'Nov 15, 2024',
 '226.40',
 '226.92',
 '224.27',
 '225.00',
 '224.75',
 '47,923,700',
 'Nov 14, 2024',
 '225.02',
 '228.87',
 '225.00',
 '228.22',
 '227.97',
 '44,923,900',
 'Nov 13, 2024',
 '224.01',
 '226.65',
 '222.76',
 '225.12',
 '224.87',
 '48,566,200',
 'Nov 12, 2024',
 '224.55',
 '225.59',
 '223.36',
 '224.23',
 '223.98',
 '40,398,300',
 'Nov 11, 2024',
 '225.00',
 '225.70',
 '221.50',
 '224.23',
 '223.98',
 '42,005,600',
 'Nov 8, 2024',
 '0.25 Dividend ',
 'Nov 8, 2024',
 '227.17',
 '228.66',
 '226.41',
 '226.96',
 '226.71',
 '38,328,800',
 'Nov 7, 2024',
 '224.63',
 '227.88',
 '224.57',
 '227.48',
 '226.98',
 '42,137,700',
 'Nov 6, 2024',
 '222.61',
 '226.07',
 '221.19',
 '222.72',
 '222.23',
 '54,561,100',
 'Nov 5, 2024',
 '221.80',
 '223.95',
 '221.14',
 '223.45',
 '222.96',
 '28,111,300',
 'Nov 4, 2024',
 '220.99',
 '222.79',
 '219.71',
 '222.01',
 '221.52',
 '44,944,500',
 'Nov 1, 2024',
 '220.97',
 '225.35',
 '220.27',
 '222.91',
 '222.42',
 '65,276,700',
 'Oct 31, 2024',
 '229.34',
 '229.83',
 '225.37',
 '225.91',
 '225.41',
 '64,370,100',
 'Oct 30, 2024',
 '232.61',
 '233.47',
 '229.55',
 '230.10',
 '229.59',
 '47,070,900',
 'Oct 29, 2024',
 '233.10',
 '234.33',
 '232.32',
 '233.67',
 '233.16',
 '35,417,200',
 'Oct 28, 2024',
 '233.32',
 '234.73',
 '232.55',
 '233.40',
 '232.89',
 '36,087,100',
 'Oct 25, 2024',
 '229.74',
 '233.22',
 '229.57',
 '231.41',
 '230.90',
 '38,802,300',
 'Oct 24, 2024',
 '229.98',
 '230.82',
 '228.41',
 '230.57',
 '230.06',
 '31,109,500',
 'Oct 23, 2024',
 '234.08',
 '235.14',
 '227.76',
 '230.76',
 '230.25',
 '52,287,000',
 'Oct 22, 2024',
 '233.89',
 '236.22',
 '232.60',
 '235.86',
 '235.34',
 '38,846,600',
 'Oct 21, 2024',
 '234.45',
 '236.85',
 '234.45',
 '236.48',
 '235.96',
 '36,254,500',
 'Oct 18, 2024',
 '236.18',
 '236.18',
 '234.01',
 '235.00',
 '234.48',
 '46,431,500',
 'Oct 17, 2024',
 '233.43',
 '233.85',
 '230.52',
 '232.15',
 '231.64',
 '32,993,800',
 'Oct 16, 2024',
 '231.60',
 '232.12',
 '229.84',
 '231.78',
 '231.27',
 '34,082,200',
 'Oct 15, 2024',
 '233.61',
 '237.49',
 '232.37',
 '233.85',
 '233.34',
 '64,751,400',
 'Oct 14, 2024',
 '228.70',
 '231.73',
 '228.60',
 '231.30',
 '230.79',
 '39,882,100',
 'Oct 11, 2024',
 '229.30',
 '229.41',
 '227.34',
 '227.55',
 '227.05',
 '31,759,200',
 'Oct 10, 2024',
 '227.78',
 '229.50',
 '227.17',
 '229.04',
 '228.54',
 '28,183,500',
 'Oct 9, 2024',
 '225.23',
 '229.75',
 '224.83',
 '229.54',
 '229.04',
 '33,591,100',
 'Oct 8, 2024',
 '224.30',
 '225.98',
 '223.25',
 '225.77',
 '225.27',
 '31,855,700',
 'Oct 7, 2024',
 '224.50',
 '225.69',
 '221.33',
 '221.69',
 '221.20',
 '39,505,400',
 'Oct 4, 2024',
 '227.90',
 '228.00',
 '224.13',
 '226.80',
 '226.30',
 '37,245,100',
 'Oct 3, 2024',
 '225.14',
 '226.81',
 '223.32',
 '225.67',
 '225.17',
 '34,044,200',
 'Oct 2, 2024',
 '225.89',
 '227.37',
 '223.02',
 '226.78',
 '226.28',
 '32,880,600',
 'Oct 1, 2024',
 '229.52',
 '229.65',
 '223.74',
 ...]

In [78]:
parsed_data_stock = parse_data(page_elements)

Skipping incomplete data at index 1750

In [79]:
parsed_data_stock[54]

{'Date': 'Feb 7, 2025',
 'Open': '232.60',
 'High': '234.00',
 'Low': '227.26',
 'Close': '227.63',
 'Volume': '39,707,200'}

In [98]:
import pandas as pd 

df = pd.DataFrame(parsed_data_stock)

In [99]:
df.head()

           Date    Open    High     Low   Close      Volume
0  Apr 28, 2025  210.06  211.50  208.73  209.74  10,697,544
1  Apr 25, 2025  206.37  209.75  206.20  209.28  38,198,600
2  Apr 24, 2025  204.89  208.83  202.94  208.37  47,311,000
3  Apr 23, 2025  206.00  208.00  202.80  204.60  52,929,200
4  Apr 22, 2025  196.12  201.59  195.97  199.74  52,976,400

In [100]:
df = df.iloc[:78]

In [101]:
df.tail()

            Date    Open    High     Low   Close      Volume
73  Jan 10, 2025  240.01  240.16  233.00  236.85  61,710,900
74   Jan 8, 2025  241.92  243.71  240.05  242.70  37,628,900
75   Jan 7, 2025  242.98  245.55  241.35  242.21  40,856,000
76   Jan 6, 2025  244.31  247.33  243.20  245.00  45,045,600
77   Jan 3, 2025  243.36  244.18  241.89  243.36  40,244,100

In [102]:
ini_string = "Apr 28, 2025"
parsed_date = re.match(r"(\w{3}) (\d{1,2}), (\d{4})", ini_string)

In [103]:
df.shape

(78, 6)

In [104]:
df.iloc[54]

Date      Feb 7, 2025
Open           232.60
High           234.00
Low            227.26
Close          227.63
Volume     39,707,200
Name: 54, dtype: object

In [105]:
for i in range(df.shape[0]):
    string = df['Date'][i]
    match = re.match(r"(\w{3}) (\d{1,2}), (\d{4})", string)
    if not match:
        print(i)

In [ ]:
def date_format(input:str):
    input = input.lower()
    month_to_number = {
    'jan': '01', 'feb': '02', 'mar': '03',
    'apr': '04', 'may': '05', 'jun': '06',
    'jul': '07', 'aug': '08', 'sep': '09',
    'oct': '10', 'nov': '11', 'dec': '12'
    }
    match = re.match(r"(\w{3}) (\d{1,2}), (\d{4})", input)
    if match:
        month_str, day, year = match.groups()
        if len(day) < 2:
            day = '0' + str(day)
        month_num = month_to_number.get(month_str, '00')
    
    return f"{year}-{month_num}-{day}"

In [107]:
df['Date'] = df['Date'].apply(date_format)

In [108]:
df['Date']

0     2025-04-28
1     2025-04-25
2     2025-04-24
3     2025-04-23
4     2025-04-22
         ...
73    2025-01-10
74    2025-01-08
75    2025-01-07
76    2025-01-06
77    2025-01-03
Name: Date, Length: 78, dtype: object